In [4]:
import numpy as np
 
# 例題の行列
A = np.array([[5, 2],
              [2, 5]])
 
# 固有値と固有ベクトルを求める。
eig, P = np.linalg.eig(A)
# print(eig)
print(P)
print(np.linalg.inv(P))
 
# 対角化
D = np.dot(np.dot(np.linalg.inv(P), A), P)
print(D)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[[7.0000000e+00 8.8817842e-16]
 [8.8817842e-16 3.0000000e+00]]
